import {storage,safeMutation,failure} from '@/lib/storage';
import type {Post} from '@/lib/types';
export async function GET(){try{const {DB}=storage();await DB.batch([
DB.prepare("INSERT OR IGNORE INTO posts (id,title,date,project,status,caption,comment,drive,assets,updated) SELECT ?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='initialized')").bind('template-example','Machine expresso','2026-09-01','FASTWAY','En attente','Exemple repris de votre template. Remplacez ce visuel par le fichier original en haute définition.','','',JSON.stringify([{id:'template',name:'Machine-expresso-exemple.jpg',url:'/template-post.jpg',type:'image/jpeg',size:0}]),new Date().toISOString()),
DB.prepare("INSERT OR IGNORE INTO settings (key,value) VALUES ('initialized','1')")]);
const {results}=await DB.prepare('SELECT * FROM posts ORDER BY date,title').all();return Response.json(results.map(p=>({...p,assets:JSON.parse(p.assets as string),thumbnail:p.thumbnail?JSON.parse(p.thumbnail as string):null})),{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e)}}
export async function POST(req:Request){try{safeMutation(req);const p=await req.json() as Post;
if(!p.id || !p.title?.trim() || p.title.length>150 || !/^\d{4}-\d{2}-\d{2}$/.test(p.date) || isNaN(Date.parse(p.date)) || !['En attente','Validé','À retravailler','Publié'].includes(p.status) || !Array.isArray(p.assets) || p.assets.length>30 || (p.drive && !/^https:\/\/(drive|docs)\.google\.com\//.test(p.drive)))return Response.json({error:'Vérifiez le titre, la date et le lien Google Drive.'},{status:400});
if(p.assets.some(a=>!a.url?.startsWith('/api/files?id=') && a.url!='/template-post.jpg'))return Response.json({error:'Fichier invalide.'},{status:400});
if(p.thumbnail && (!/^image\/(png|jpeg|webp|gif)$/.test(p.thumbnail.type) || (!/^\/api\/files\?id=[a-z0-9-]{36}$/.test(p.thumbnail.url) && p.thumbnail.url!='/template-post.jpg')))return Response.json({error:'Choisissez une miniature PNG, JPEG, WebP ou GIF.'},{status:400});
const {DB}=storage();const updated=new Date().toISOString();await DB.prepare('INSERT INTO posts (id,title,date,project,status,caption,comment,drive,assets,updated,thumbnail) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,date=excluded.date,project=excluded.project,status=excluded.status,caption=excluded.caption,comment=excluded.comment,drive=excluded.drive,assets=excluded.assets,updated=excluded.updated,thumbnail=excluded.thumbnail').bind(p.id,p.title.trim(),p.date,p.project?.trim()||'FASTWAY',p.status,(p.caption||'').slice(0,20000),(p.comment||'').slice(0,20000),p.drive||'',JSON.stringify(p.assets),updated,p.thumbnail?JSON.stringify(p.thumbnail):null).run();return Response.json({...p,updated});}catch(e){return failure(e)}}
export async function DELETE(req:Request){try{safeMutation(req);const {id}=await req.json() as {id:string};if(!id)return Response.json({error:'Identifiant manquant'},{status:400});await storage().DB.prepare('DELETE FROM posts WHERE id=?').bind(id).run();return Response.json({ok:true});}catch(e){return failure(e)}}
